<?php

namespace WCS\PropertyBundle\Repository;

/**
 * ProfImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfImagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getImages($profId)
    {

        $qb = $this->createQueryBuilder('path');

        $qb->select('path.primProfId as profId')
        ;
    
        return $qb->getQuery()->getResult();    
    }
}