<?php

namespace WCS\EmailingBundle\Repository;

/**
 * EmailUserListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailUserListingRepository extends \Doctrine\ORM\EntityRepository
{

}