<?php

namespace WCS\EmailingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailUserListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailUserListingRepository extends EntityRepository
{
}
