<?php

namespace WCS\RatingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RatingPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingPropertyRepository extends EntityRepository
{
}
